export interface Product {
  id: string;
  slug: string;
  name: string;
  category: "ring" | "earring";
  collection: string;
  price: number;
  mrp?: number;
  images: string[];
  metal: string;
  dimensions: string;
  weight: string;
  finish: string;
  inspiration: string;
  stock: number;
  isNew: boolean;
  isFeatured: boolean;
  description: string;
  care: string;
}

export const products: Product[] = [
  {
    id: "1",
    slug: "adiva-forest-ring",
    name: "Adiva Forest Ring",
    category: "ring",
    collection: "Adiva",
    price: 2840,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80&auto=format",
    ],
    metal: "Sterling Silver 925",
    dimensions: "18mm × 22mm",
    weight: "6.8g",
    finish: "Hand-oxidized, matte",
    inspiration: "Gond tribal dot art patterns from Madhya Pradesh forests",
    stock: 3,
    isNew: false,
    isFeatured: true,
    description: "A bold statement ring inspired by the forest motifs of Gond tribal art. Each dot and curve is hand-etched into sterling silver, creating a piece that feels ancient yet utterly modern.",
    care: "Store in the provided cotton pouch. Avoid contact with perfumes and water. Clean gently with a soft dry cloth.",
  },
  {
    id: "2",
    slug: "nilam-drop-earrings",
    name: "Nilam Drop Earrings",
    category: "earring",
    collection: "Adiva",
    price: 1650,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
    ],
    metal: "Oxidized Brass",
    dimensions: "45mm × 15mm",
    weight: "4.2g",
    finish: "Oxidized with tourmaline accent",
    inspiration: "Water droplets on lotus leaves — a motif sacred in Gond cosmology",
    stock: 8,
    isNew: true,
    isFeatured: true,
    description: "Elongated drop earrings featuring oxidized brass with a tourmaline stone accent. The teardrop silhouette draws from nature motifs central to Gond mythology.",
    care: "Remove before showering. Store separately to avoid scratching. Polish with brass cleaning cloth as needed.",
  },
  {
    id: "3",
    slug: "prithvi-stacking-band",
    name: "Prithvi Stacking Band",
    category: "ring",
    collection: "Adiva",
    price: 1290,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80&auto=format",
    ],
    metal: "Recycled Silver",
    dimensions: "3mm band width",
    weight: "3.1g",
    finish: "Polished with dot texture",
    inspiration: "Gond dot motif representing earth (Prithvi) and its rhythms",
    stock: 15,
    isNew: false,
    isFeatured: true,
    description: "A delicate stacking band featuring the signature Gond dot pattern. Made from recycled silver — wear one alone for subtlety, or stack three for impact.",
    care: "Store flat in a dry place. Clean with silver polish cloth. Avoid harsh chemicals.",
  },
  {
    id: "4",
    slug: "aarav-hoop-earrings",
    name: "Aarav Hoop Earrings",
    category: "earring",
    collection: "Adiva",
    price: 1480,
    images: [
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
    ],
    metal: "Hammered Brass",
    dimensions: "32mm diameter",
    weight: "5.4g",
    finish: "Hammered with forest green enamel",
    inspiration: "The circular rhythms of tribal dance — Gond celebrations of harvest",
    stock: 4,
    isNew: true,
    isFeatured: true,
    description: "Textured hoop earrings in hammered brass with a striking forest green enamel inlay. The imperfect surface celebrates handcraft over machine precision.",
    care: "Avoid prolonged water exposure. Enamel is delicate — store in individual compartments.",
  },
  {
    id: "5",
    slug: "vana-statement-ring",
    name: "Vana Statement Ring",
    category: "ring",
    collection: "Adiva",
    price: 3200,
    mrp: 3800,
    images: [
      "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80&auto=format",
    ],
    metal: "Mixed Metal (Silver + Brass)",
    dimensions: "24mm × 28mm",
    weight: "9.2g",
    finish: "Dual-tone oxidized",
    inspiration: "Tribal weave patterns representing the interconnected forest canopy",
    stock: 2,
    isNew: false,
    isFeatured: true,
    description: "Our most dramatic piece — a mixed-metal statement ring featuring an interlocking tribal weave pattern. The contrast of silver and brass creates a piece that commands attention.",
    care: "Avoid chemicals and perfumes. Wipe with dry cloth after wearing. Store in provided box.",
  },
  {
    id: "6",
    slug: "sundari-jhumka-earrings",
    name: "Sundari Jhumka Earrings",
    category: "earring",
    collection: "Adiva",
    price: 1890,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
    ],
    metal: "Sterling Silver 925",
    dimensions: "52mm × 20mm",
    weight: "7.1g",
    finish: "Antique silver with ghungroo detailing",
    inspiration: "Temple bell silhouettes and the rhythm of ghungroos in classical dance",
    stock: 6,
    isNew: false,
    isFeatured: false,
    description: "A modern interpretation of the classic jhumka, featuring miniature ghungroo clusters that catch light with every movement. Substantial without being heavy.",
    care: "Clean with silver polish. Avoid contact with water and cosmetics.",
  },
  {
    id: "7",
    slug: "kavya-ear-cuff",
    name: "Kavya Ear Cuff",
    category: "earring",
    collection: "Adiva",
    price: 980,
    images: [
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
    ],
    metal: "Brass",
    dimensions: "18mm × 12mm",
    weight: "2.3g",
    finish: "Gold-plated with micro dots",
    inspiration: "The spiral patterns found in Gond art representing eternal growth",
    stock: 12,
    isNew: true,
    isFeatured: false,
    description: "A no-pierce ear cuff with delicate Gond spiral etching. Adjustable to fit any ear — for those who want to make a quiet statement.",
    care: "Gold plating is delicate. Avoid water, perfume, and lotions. Store in a soft pouch.",
  },
  {
    id: "8",
    slug: "meera-chandelier-earrings",
    name: "Meera Chandelier Earrings",
    category: "earring",
    collection: "Adiva",
    price: 2450,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
    ],
    metal: "Oxidized Silver",
    dimensions: "65mm × 30mm",
    weight: "8.5g",
    finish: "Deep oxidized with mirror chips",
    inspiration: "Gond depictions of the Tree of Life — branches reaching toward light",
    stock: 3,
    isNew: false,
    isFeatured: false,
    description: "Dramatic chandelier earrings with cascading tribal branches and embedded mirror chips. An evening piece that moves with grace and catches every light.",
    care: "Handle with care. Mirror chips are fragile. Store in padded box. Avoid dropping.",
  },
  {
    id: "9",
    slug: "dhara-signet-ring",
    name: "Dhara Signet Ring",
    category: "ring",
    collection: "Adiva",
    price: 2100,
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80&auto=format",
    ],
    metal: "Sterling Silver 925",
    dimensions: "20mm face",
    weight: "7.5g",
    finish: "Matte with engraved Gond peacock",
    inspiration: "The peacock — Gond symbol of beauty, rain, and fertility",
    stock: 5,
    isNew: true,
    isFeatured: false,
    description: "A modern signet ring featuring a hand-engraved Gond peacock motif. Flat face, comfortable band — wear it as your daily signature piece.",
    care: "Silver may develop patina over time — this is intentional. Polish if desired, or let it age naturally.",
  },
  {
    id: "10",
    slug: "tara-chain-earrings",
    name: "Tara Chain Earrings",
    category: "earring",
    collection: "Adiva",
    price: 1320,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
    ],
    metal: "Brass with Silver Dip",
    dimensions: "70mm length",
    weight: "3.8g",
    finish: "Mixed finish — matte top, polished chain",
    inspiration: "Falling stars in Gond night sky paintings",
    stock: 9,
    isNew: false,
    isFeatured: false,
    description: "Minimalist chain earrings with a tribal stud top and delicate hanging chain. Light enough for all-day wear — movement and shimmer in every step.",
    care: "Chains are delicate. Store untangled in soft pouch. Avoid pulling or stretching.",
  },
  {
    id: "11",
    slug: "rudra-band-ring",
    name: "Rudra Band Ring",
    category: "ring",
    collection: "Adiva",
    price: 1750,
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80&auto=format",
    ],
    metal: "Oxidized Brass",
    dimensions: "8mm band width",
    weight: "5.6g",
    finish: "Deep oxidized with geometric incisions",
    inspiration: "Gond geometric patterns representing the cosmic order",
    stock: 7,
    isNew: false,
    isFeatured: false,
    description: "A bold band ring with deeply incised geometric patterns drawn from Gond cosmological art. The wide band makes a strong, grounded statement.",
    care: "Brass oxidizes naturally. Clean with lemon and salt paste for a fresh look, or embrace the aged patina.",
  },
  {
    id: "12",
    slug: "anaya-stud-earrings",
    name: "Anaya Stud Earrings",
    category: "earring",
    collection: "Adiva",
    price: 890,
    images: [
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80&auto=format",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&auto=format",
    ],
    metal: "Sterling Silver 925",
    dimensions: "10mm × 10mm",
    weight: "2.0g",
    finish: "High polish with Gond sun motif",
    inspiration: "The sun — central to Gond paintings as giver of life",
    stock: 20,
    isNew: true,
    isFeatured: false,
    description: "Petite stud earrings featuring the Gond sun motif. The perfect entry point into the Adiva collection — subtle, meaningful, everyday wearable.",
    care: "Wipe after each wear with soft cloth. Store in airtight pouch to prevent tarnishing.",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}
